### ISSUE TITLE
Licensing exception (similar to GNU Autotools)?

### ISSUE THREAD

**Issue by jsquyres** [c3d/build#2]
Will there be a licensing exception for distributing build with projects that use it for building themselves (similar to the GNU Autotools exception: https://www.gnu.org/software/autoconf/manual/autoconf.html#Distributing)?

Thanks!

**Comment by c3d** [comment]
I do not feel that a licensing exception is needed, because the build system is usually independent from the product being built. In other words, my understanding is that using 'build' does not require your product to be GPL-compliant, no more than using gmake or gcc to build it. But a clarification of my understanding may be needed. I will add it to the README file.

**Comment by c3d** [comment]
Clarified in https://github.com/c3d/build/commit/60609d0f2c8f054e918e1803d861f68e9bae0c12.

**Comment by jsquyres** [comment]
Thanks for the clarification!
