### ISSUE TITLE
Allow standard make variables like CC, LD, etc to be specified before rules.mk

### ISSUE THREAD

**Issue by kanaka** [c3d/build#5]
Standard makefile definitions like CC, LD, etc should probably be specified in rules.mk using "?=" so that they can be defined prior to the `include $(BUILD)rule.mk`.

**Comment by c3d** [comment]
I am conflicted about this suggestion, because doing as you suggest creates makefiles that are not portable. In other words, you hard-coded the compiler in the makefile, and then you don't benefit from the mechanisms to switch between compilers.

What is wrong in your use case with creating a `config.myconfig.mk` that defines `CC` and `LD` the way you want, possibly after including `config.base.mk`? That way, you would select the set of tools you want with `BUILDENV=myconfig`?

**Comment by c3d** [comment]
I close this one for now, feel free to reopen if you think there is something else that should be done. Thanks.
